ALTER TYPE "BookingStatus" ADD VALUE IF NOT EXISTS 'PAID';
ALTER TYPE "BookingStatus" ADD VALUE IF NOT EXISTS 'CHECK_IN';
ALTER TYPE "BookingStatus" ADD VALUE IF NOT EXISTS 'CHECKOUT';

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'userrole') THEN
    CREATE TYPE "UserRole" AS ENUM ('USER', 'ADMIN');
  END IF;
END $$;

ALTER TABLE "users"
  ADD COLUMN IF NOT EXISTS "role" "UserRole" NOT NULL DEFAULT 'USER';

ALTER TABLE "camps"
  ADD COLUMN IF NOT EXISTS "daily_capacity" INTEGER NOT NULL DEFAULT 100;

ALTER TABLE "bookings"
  ADD COLUMN IF NOT EXISTS "people_count" INTEGER NOT NULL DEFAULT 1;
